"""
Research Exporter — Export Kiwi research sessions to Markdown files.
"""

import re
from datetime import datetime
from pathlib import Path

EXPORT_DIR = Path.home() / ".kiwi" / "exports"


class ResearchExporter:
    """Export research sessions to Markdown."""

    def __init__(self):
        EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    def export_markdown(
        self,
        query: str,
        plan: str,
        response: str,
        score: float,
        critique_data: dict,
        refined: bool = False,
        thread_name: str | None = None,
    ) -> Path:
        """Export a research session to a timestamped Markdown file."""
        now = datetime.now()
        slug = re.sub(r"[^\w\s-]", "", query[:50]).strip().replace(" ", "_").lower()
        filename = f"{now.strftime('%Y%m%d_%H%M%S')}_{slug}.md"
        filepath = EXPORT_DIR / filename

        dims = critique_data.get("dimension_scores", {})
        dim_table = "\n".join(
            f"| {k.replace('_', ' ').title()} | {v:.2f} |"
            for k, v in dims.items()
        )

        content = f"""# Kiwi Research Export
**Query:** {query}
**Date:** {now.strftime('%B %d, %Y %H:%M')}
**Quality Score:** {score:.2f} {'(Refined)' if refined else ''}
{f'**Thread:** {thread_name}' if thread_name else ''}

---

## Research Plan

{plan}

---

## Research Response

{response}

---

## Quality Assessment (Ralph Wiggum Loop)

| Dimension | Score |
|-----------|-------|
{dim_table}
| **Composite** | **{score:.2f}** |

**Strengths:**
{chr(10).join(f"- {s}" for s in critique_data.get("strengths", []))}

**Critical Issues Addressed:**
{chr(10).join(f"- {i}" for i in critique_data.get("critical_issues", [])) or "None"}

---

*Generated by Kiwi — Performance Research Architect*
*Model: claude-opus-4-6 with adaptive thinking*
"""

        filepath.write_text(content)
        return filepath

    def list_exports(self) -> list[Path]:
        """List all exported research files."""
        return sorted(EXPORT_DIR.glob("*.md"), reverse=True)
